### ISSUE TITLE
Add configuration maybe?

### ISSUE THREAD

**Issue by amatiasq** [brandonweiss/charge#1095]
### Thanks

Hi! first of all thanks for creating this project, I've spent the last months [looking for a SSG generator](https://github.com/amatiasq/ssg-comparison/) like this one without much success.

### Background 

There are some features I would like to behave differently so I've forked your project and [implemented one of them](https://github.com/amatiasq/charge/commit/98c8ce00129fb6577920a319326956ed38ce4f3c) (transform `myfile.html.mdx` into `myfile/index.html`) and more changes will land soon.

### Settings

I understand why this should not be the default behaviour so if this is ever to be merged back into Charge it should be under a setting IMHO.

AFAIK you don't want this tool to be configurable and I understand that point, just wanted to doble check while also tasting the community interest in having configuration options for Charge.

### Proposals

This can be done with a `.chargerc.json` file as many other tools but it's not my favourite option. I think CLI parameters would work great for a tool like this (`charge --pages-as-directories serve`?)

**Comment by amatiasq** [comment]
I need my website in two languages so some kind of i18n will land on the fork too.

**Comment by brandonweiss** [comment]
Hey! Regarding the `myfile/index.html`, can you explain the use-case for that? Like what specifically are you trying to achieve by changing the output structure?

And can you give me an overview of how you’d expect i18n to work? What would the URL structure look like? What would the file structure look like? Would there be different MDX files for every language? Would there be one file with key names that pull from a translations file? Et cetera.

Thanks!

**Comment by amatiasq** [comment]
## Pages as directories

The motivation behind the directory structure change is so that the public url is simpler for the final user

```
https://mydomain.com/about-me
```
(`/index.html` being implicit) vs
```
https://mydomain.com/about-me.html
```

This  s something already done by other tools like 11ty (see how [test.html](https://github.com/amatiasq/ssg-comparison/blob/main/11ty/src/test.html) becomes [a directory](https://github.com/amatiasq/ssg-comparison/tree/main/11ty/dist/test)).

## i18n
I want my site to generate 3 representations of each page, for example:

```
/about-me
/en/about-me
/es/about-me
```

Hopefully the one without language code (`/about-me`) just returns HTTP code 301 redirect to the url with the default language (`/en/about-me`) or vice versa (this would be nginx config) but it works for me too if they are just two copies of the same page.

I haven't settled to an approach yet on this topic.

## Pages directory
I'm also a little bit bothered by the fact that if we import files outside the `source` directory when we run `charge serve source` they don't get removed from NodeJS cache so we need to stop the process and start it again in order to load the changes. For example

```jsx
// source/index.html
import Layout from '../components/layout'
export default () => <Layout>My Content</Layout>;
```

If I start the `serve` process and later change `components/layout.jsx` the changes won't be reflected. At the same time I don't want to put `layout.jsx` inside de `source` directory because Charge will process it and add it to the output directory.

I will probably address this by only processing files under `source/pages` while the watch process will remove the NodeJS cache for every file under `source` on every filesystem event.

I'm **currently** trying to implement this while making as little changes as possible, this is also a candidate for configuration and if this change is implemented maybe we can also move `data` directory into the `source` directory too leaving, to my eyes, a cleaner project structure:

```
/.github (or any CI config)
/node_modules
/package.json
/package-lock (or yarn.lock)
/tmp
/src
  /pages
  /components
  /data
```

## Data files
I write my data files in markdown with [front-matter](https://www.npmjs.com/package/front-matter) for metadata so I will probably add support for that too. I'm considering how to add multiple languages for the markdown content itself. I haven't reached a conclusion yet but an example would be something like this (`/data/projects/lulas.md`):

```md
---
key: lulas
date: 2011-01-01

name:
  en: Lulas (cell simulation)
  es: Lulas (simulación celular)

links:
  live: https://repos.amatiasq.com/lulas/
  github: https://github.com/amatiasq/lulas/
  tests: https://coveralls.io/github/amatiasq/lulas

labels:
  - TDD
  - Typescript
  - Canvas
  - Jest
---

A simulation of cells hunting each other. There are three kind of cells: Plants (dark green), Herbivores (light green) and Hunters (red).

Development paused while working on [Version 2](https://amatiasq.github.io/lulas) in order to simplify implementation of more complex
behavior like flocking behavior.

---

Un simulador de células cazándose entre ellas. Hay tres tipos de células: Plantas (verde obscuro), Hervívoros (verde claro) y Cazadores (rojo).

El desarrollo se ha pausado mientras se desarrollaba la [Versión 2](https://amatiasq.github.io/lulas) para simplificar la implementación de comportamiento más complejo como comportamiento de bandada.
```

## Already pushed
I've pushed two more commits, [one](https://github.com/amatiasq/charge/commit/ac1af02193eb7acf58c38f4cb90d32eb24085c97) to actually print the complete error callstack and not crash the watcher when an error occurs and [another](https://github.com/amatiasq/charge/commit/cfdf58f9cff71fed90af46cced8da47c2bda89c6) changing `let` and `var` declarations to `const` whenever possible. I did this for my own sanity because that way I **know** when I see `let` that I'm looking at a variable that might change in the future, while when I see `const` I know I'm looking at the definitive value of the variable.

**Comment by brandonweiss** [comment]
Okay so regarding the file structure (pages as directories), did you happen to read the section in the docs on [clean URLs](https://charge.js.org/concepts) (it’s at the bottom)?

Generally speaking, clean URLs are a deployment concern. All modern static hosts (Netlify, Vercel, et cetera) and most web servers (nginx, Apache, Caddy, et cetera) support clean URLs without having to futz with the file structure a static site generator outputs. Can you tell me what or how you’re hosting your site?

As for the other ideas, would you mind opening separate issues for each of them? It’ll make it much easier to talk about them separately. Thanks!

**Comment by amatiasq** [comment]
No, I didn't read that, I wouldn't expect to find it under "Concepts" either, maybe at the bottom of "Usage" or even "Deployment" section might make it easier to find.

It's true that it is a deployment concern but we can solve it out of the box with zero configuration and being deployment agnostic. I will start by deploying it to GH pages for simplicity but I might move them to Vercel or my own Nginx depending on the situation.

I agree to split this up to different issues but I would like to know two things:

- Are you open to add configuration? if so do you agree to do it as CLI options?
- Would you be interested in merging the already implemented changes? any other feature will be implemented on top of them. Otherwise I might just save the time and document them on the fork.

**Comment by brandonweiss** [comment]
Yeah, perhaps that’s not the best location—I’ll have a think about moving it somewhere else.

I know it seems like you’re solving a problem by using the Directory Indexes pattern to get clean URLs, but that pattern causes a bunch of subtle, less obvious problems. Charge actually [started out](https://github.com/brandonweiss/charge/commit/2ce3d7ac8937963f4885f94cdfb4b47e22965952) using the Directory Indexes pattern and I specifically moved away from it later on after I ran into issues. It’s been a long time so I can’t remember what they exactly were, but it had something to do with deployment… I think several common static site hosts don’t handle directory indexes in the way you’d necesarily expect. That’s when I had the epiphany that clean URLs are really a deployment concern.

Regarding configuration, I would say that considering the entire premise of the project is that it’s a zero-configuration static site generator, the answer is probably no, but I guess it would be more fair to say I’m always open to considering something, but the bar to adding configuration would be pretty high.

Regarding upstreaming your changes so far…

* I wouldn’t upstream the Directory Indexes stuff for the reason I mentioned above
* I would upstream the Prettier config but I personally use different settings so I would tweak them first
* I don’t quite understand the error reporting changes you made, but if they make sense I’d definitely upstream them
* I probably wouldn’t upstream the let/const changes—when I wrote this project I was using let/const semantically, that is `const` is for actual constants and `let` is for normal variables. On other projects I use the slightly more common pattern of using `const` for variables you never re-assign, and `let` for variables you do reassign. I’m not dogmatic about either one—I think both patterns have merit—but I see them as being mostly a subjective matter of taste and style, and I don’t really think it’s worth changing from one subjective style to another because someone is always going to be unhappy about it.

**Comment by amatiasq** [comment]
Fair enough, I can't imagine what could be the issues you ran up to with Clean URLs, maybe something related to the warning in [this section?](https://www.11ty.dev/docs/permalinks/#remapping-output-(permalink))

I think having zero configuration tools is a great advantage that would mean these changes would be irreconciliable with the current implementation.

So from the changes we're talking about merging only the prettier config after some changes, that means I'll have to make a complete fork then, thank you for your time and effort.

### Into the depths of programming philosophy

Regarding the variables I think what you call "semantic" use of `let/const` is actually subjective, you can notice that by the expressions "actual" and "normal" in 

> `const` is for actual constants and `let` is for normal variables

After all, a variable that doesn't change is by definition a constant, to put it in perspective you can see how objective it is to say

> `const` is for values that never change, `let` is for variables that mutate

I'm not dogmatic about it either but since I'm the one implementing the changes I need the code to give me as much information about itself as possible.
