### ISSUE TITLE
Node engine version

### ISSUE THREAD

**Issue by fannarsh** [brandonweiss/charge#119]
It would be nice to move the node engine version down to 8.10.0.
According to https://node.green/ versions 8.10.0 to 9.11.2 are the same in terms of compatibility.
By moving the engine requirement down to 8.10.0 we will be able to create a static build on [Zeit Now 2.0](https://zeit.co/blog/now-2)

**Comment by brandonweiss** [comment]
@fannarsh You’re right! Done!

And please let me know if you run into any issues or see any areas for improvement. I soft-released Charge so I could get some feedback and fix any bugs. I’m actually amazed anyone found this repo without me talking about it. 😂 I have a small list of improvements that I’d like to make and then I’ll start telling more people about it.
