### ISSUE TITLE
CSS import

### ISSUE THREAD

**Issue by signalwerk** [brandonweiss/charge#383]
Is there an option to import a CSS like in other stacks? I know about `@emotion/styled`. I just search an option to reuse components form create-react-app

## example 
```jsx
import from "./styles.css"   // 🧨 here

export default ({text}) => (
  <div className="Tooltip">
    {text}
  </div>
)
```

**Comment by brandonweiss** [comment]
There isn’t—I considered it but there are a few different ways to import CSS into a JS file and it wasn’t really clear to me that they provided sufficient value over classic CSS (linking to a stylesheet in HTML) or CSS in JS (e.g. styled-components or emotion).

Let me know if there’s a usage or benefit I’m not understanding, but in your example, couldn’t you just link the stylesheet in the `<head>` of the document?

```html
<head>
  <link href="/styles.css" rel="stylesheet" />
</head>
```

**Comment by signalwerk** [comment]
@brandonweiss thank you for your answer. I'm aware of the `<link />` option and had to do it like that. The components are with this method no «self-containing» and I have to side load. But I guess that's the way I'll go for now. Thank you.
