### ISSUE TITLE
Is it possible to provide the parsed HTML for a page as a string in addition to component in the page object?

### ISSUE THREAD

**Issue by qutang** [brandonweiss/charge#496]
Now it can only access the React component object for a page in the `pages` object.

It would be flexible if we can also get the parsed HTML content for a page when we want to use the content of a page in files other than `jsx` and `mdx`.

**Comment by brandonweiss** [comment]
Possibly… although I don’t think I understand your use-case well-enough. Can you give me a specific explanation and example (ideally with code) of how you’d like to use the parsed HTML? Thanks!

**Comment by qutang** [comment]
I encountered this problem at first because I want to automatically create a short excerpt from the content and use it in the blog list or RSS feed.

There can be some other cases. For example, I would need to access the raw or parsed content of a post for text analysis, if I want to extract categories and tags from the content of a post _automatically_.

**Comment by brandonweiss** [comment]
Got it! Thanks for explaining. I have to do something similar in a project or two, and this is an example of how I do it:

```javascript
import ReactDOMServer from "react-dom/server"
import { JSDOM } from "jsdom"

let element = React.createElement(page.component)
let html = ReactDOMServer.renderToStaticMarkup(element)

// Then you have a string of HTML you can do whatever you like with.
// If you want a really structured way of interacting with it, you can use jsdom.

let firstParagraph = new JSDOM(html).window.document.querySelector("p:first-of-type").innerHTML
```

Given it’s so simple to render the component to a string, I don’t think it’s worth creating a convenience property for this yet. I try to avoid adding conveniences like this to projects until it becomes really clear that _a lot_ of people need it. I’ll definitely keep it in mind for the future, though. Thanks!

**Comment by qutang** [comment]
I did the same, in a`. js` file. The only issue is now I have to install `react` and `react-dom` as dependencies (unless it is a `jsx` or `mdx` file I guess), which sounds anti-pattern considering about what the project is trying to solve for the users. Maybe you can consider making `React` and `ReactDOMServer` object always available to the files, although I'm not sure how.

**Comment by brandonweiss** [comment]
Well, `react` and `react-dom` are already dependencies of Charge, so you might just be able to require them without installing them. Although generally speaking, it might be a good idea to install them anyways so it’s clear what dependencies you’re using.

It’s obviously subjective, but I wouldn’t consider installing a few dependencies to be antithetical to Charge’s philosophy. There’s always going to be _something_ custom you need to do in order to build the site you want. I just want it to be easy to immediately get started and not require any thought about how things should be configured.
