### ISSUE TITLE
Cannot get Emotion working

### ISSUE THREAD

**Issue by rfestag** [brandonweiss/charge#637]
I tried a simple example of using emotion, but the styling doesn't seem to work as expected. Oddly, when I inspect the page, I'm seeing elements with the appropriate styling applied (at least as the inspector sees it), but anything from the rule itself doesn't apply. As an example, I created a simple element with a background-image and a fixed height. The render height remained 0.

Do you have an example of using Emotion?

**Comment by brandonweiss** [comment]
Hey! Yeah, my very small [personal site](https://github.com/brandonweiss/brandonweiss) is using Charge with Emotion—that might be a good example to look at.

Did that help? If not, if you can point me to a repo/commit or paste a condensed example of what you’re doing here I might be able to help more.

**Comment by rfestag** [comment]
Sorry for the delayed response, I didn't see a notification that you replied. I'll take a look and see if I can get mine working or provide a simple way to reproduce it.
