### ISSUE TITLE
Feature Request: JSON alternatives?

### ISSUE THREAD

**Issue by clsource** [brandonweiss/charge#861]
Hello I have successfully used Charge in my website. Mainly for displayed projects using json data.

Some alternatives (supersets) of JSON could be used to ease the data creation.

https://github.com/hjson/hjson-js
https://github.com/json5/json5

But maybe a simple js file that exports an object could work for data too.
It would be helpful specially for multiline strings.

Thanks for this awesome project 👍

**Comment by brandonweiss** [comment]
Hey! Sorry I didn’t get back to you sooner 😓 

Yeah, I hear you, writing JSON sort of sucks. I’m constantly trying to comment out lines and/or having to fiddle with trailing commas as I add or remove data, which is super annoying.

I’m tangentially aware of the idea behind JSON supersets but I’ve never used one directly. Conceptually I love the idea, it’s just in practice I feel like it opens up a whole can of worms. Do I choose one superset or support all of them? Which is more/less confusing, supporting the superset under the `.json` extension or with a different extension? Will people get confused as to what a superset is and why something does or does not work for them in different extensions? It feels like it could be quite confusing for some people.

Allowing JS files that export an object as data files is interesting though… aside from the better ergonomics of working with a JavaScript object, it sort of dovetails into #864. It could be a nice way for people to do dynamic data fetching 🤔
